### ISSUE TITLE
Dart Syntax Convention

### ISSUE THREAD

**Issue by esutko** [arltech2017/gbg_controller#2]
in Dart curly brackets are used like this 
https://www.dartlang.org/guides/language/effective-dart/style

```dart
void function {
      return "Hello World!";
}
````

and

```dart
if true {
      return "Hello World!";
} else {
      return "Good bye world";
}
````

instead of C convention

```java
public void method 
{
   return "Hello World";
}
```

most programmers prefer the former, but the AP test uses the C convention because it is easier to read for begginers.

**Comment by ATLEASTIMNOTBLOODYELLISSUTKO** [comment]
BS. In C, I generally write in one line if the code is going to be shared with anyone as pretentious as @esutko
